#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 18 15:03:02 2019

@author: matthewrispoli
"""
import numpy as np
#from scipy.linalg import expm
import matplotlib.pyplot as plt
import matplotlib as mpl

import os
cdir=os.getcwd()
os.chdir('../..')
from plot_colors import *
os.chdir(cdir)

mpl.rc('font', **fontImp)
mpl.rc('lines', **lineSty)

def blendClr(color1,color2,alphaVal):
    return np.array(color1)*alphaVal + np.array(color2)*(1-alphaVal)


def ujC(mu,n):
    return (mu-n+1)*(n-mu)/((n+1)*(mu-n+1)+(n-mu)*n)

[XL,XH,YL,YH] = [0,0.25,0,4.0]
[XW,YT]=[XH-XL,YH-YL]

W=XW/2
H=FY
AR=XW/YT

fig = plt.figure(figsize=(FX, FY))

ax1 = fig.add_subplot(121, aspect='auto')
mus1=np.linspace(0,1,100)
ax1.plot(ujC(mus,1),mus)
